version: "3.4"

services:
  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - "82:80"
    volumes:
      - ./../back:/var/www/html
      - ./nginxfpm/asset/default.conf:/etc/nginx/conf.d/default.conf

  php:
    image: ${CONTAINER_PHP}
    user: root
    #    command: tail -f /dev/null
    restart: always
#    ports:
#      - 9000:9000
    env_file:
      - .env
      - ./../back/.env
    volumes:
      - ./../back:/var/www/html
      - ./php8/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
      - ./php8/php.ini:/usr/local/etc/php/php.ini
  db:
    image: mysql:latest
    hostname: db.${CFG_ENVIRONMENT}
    command: --default-authentication-plugin=mysql_native_password
#    ports:
#      - 8083:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
#  phpmyadmin:
#    image: phpmyadmin/phpmyadmin
#    ports:
#      - "8082:80"
#    environment:
#      PMA_HOST: ${DB_HOST}
#      MYSQL_USER: ${DB_USER}
#      MYSQL_PASSWORD: ${DB_PASSWORD}
